-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua

vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
vim.keymap.set("n", ";", ":")
vim.keymap.set("c", "Q", "q")

vim.keymap.set("n", "<leader>t", function()
  vim.cmd.vnew()
  vim.cmd.term()
  vim.cmd.wincmd("J")
  vim.api.nvim_win_set_height(0, 5)
end, { desc = "Open Terminal" })

-- new file
vim.keymap.set("n", "<leader>f", "<cmd>enew<cr>", { desc = "New File" })

-- Move Lines
vim.keymap.set("n", "<A-Down>", "<cmd>execute 'move .+' . v:count1<cr>==", { desc = "Move Down" })
vim.keymap.set("n", "<A-Up>", "<cmd>execute 'move .-' . (v:count1 + 1)<cr>==", { desc = "Move Up" })
vim.keymap.set("i", "<A-Down>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move Down" })
vim.keymap.set("i", "<A-Up>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move Up" })
vim.keymap.set("v", "<A-Down>", ":<C-u>execute \"'<,'>move '>+\" . v:count1<cr>gv=gv", { desc = "Move Down" })
vim.keymap.set("v", "<A-Up>", ":<C-u>execute \"'<,'>move '<-\" . (v:count1 + 1)<cr>gv=gv", { desc = "Move Up" })

-- Remove keymaps
vim.keymap.del("n", "<leader>K")
vim.keymap.del("n", "<leader>l")
vim.keymap.del("n", "<leader>L")
vim.keymap.del("n", "<leader>ur")
vim.keymap.del("n", "<leader>uf")
vim.keymap.del("n", "<leader>uF")
vim.keymap.del("n", "<leader>us")
vim.keymap.del("n", "<leader>uw")
vim.keymap.del("n", "<leader>uL")
vim.keymap.del("n", "<leader>ud")
vim.keymap.del("n", "<leader>ul")
vim.keymap.del("n", "<leader>uc")
vim.keymap.del("n", "<leader>uA")
vim.keymap.del("n", "<leader>uT")
vim.keymap.del("n", "<leader>ub")
vim.keymap.del("n", "<leader>uD")
vim.keymap.del("n", "<leader>ua")
vim.keymap.del("n", "<leader>ug")
vim.keymap.del("n", "<leader>uS")
vim.keymap.del("n", "<leader>uh")
vim.keymap.del("n", "<leader>ui")
vim.keymap.del("n", "<leader>uI")
vim.keymap.del("n", "<leader>uz")
vim.keymap.del("n", "<leader>uZ")
vim.keymap.del("n", "<leader>up")
vim.keymap.del("n", "<leader>-")
vim.keymap.del("n", "<leader>dpp")
vim.keymap.del("n", "<leader>dph")
vim.keymap.del("n", "<leader>`")
vim.keymap.del("n", "<leader>fT")
vim.keymap.del("n", "<leader>ft")
vim.keymap.del("n", "<leader>fn")
vim.keymap.del("n", "<leader>bb")
vim.keymap.del("n", "<leader>bD")
vim.keymap.del("n", "<leader>be")
vim.keymap.del("n", "<leader>bl")
vim.keymap.del("n", "<leader>bo")
vim.keymap.del("n", "<leader>bP")
vim.keymap.del("n", "<leader>br")
vim.keymap.del("n", "<leader>cd")
vim.keymap.del("n", "<leader><tab>l")
vim.keymap.del("n", "<leader><tab>o")
vim.keymap.del("n", "<leader><tab>f")
vim.keymap.del("n", "<leader><tab><tab>")
vim.keymap.del("n", "<leader><tab>]")
vim.keymap.del("n", "<leader><tab>d")
vim.keymap.del("n", "<leader><tab>[")
vim.keymap.del("n", "[B")
vim.keymap.del("n", "]B")
vim.keymap.del({ "n", "t" }, "<c-_>")
vim.keymap.del("n", "<C-/>")
vim.keymap.del("n", "<S-h>")
vim.keymap.del("n", "<S-l>")
vim.keymap.del("i", ",")
vim.keymap.del("i", ".")
vim.keymap.del("i", ";")
vim.keymap.del("n", "<leader>wm")
vim.keymap.del({ "n", "x" }, "<leader>gB")
vim.keymap.del({ "n", "x" }, "<leader>gY")
vim.keymap.del("n", "<leader>ge")
